import time,pytest
from playwrightTestingPractice.utils.utility import user_credentials,user_login

from playwrightTestingPractice.pages.homepage import Homepage
from playwrightTestingPractice.pages.checkout_information_order_confirmation_page import Orderpage
from playwrightTestingPractice.pages.shoppingcart import Shoppingcart
from playwrightTestingPractice.pages.orderhistory import Orderhistory
from playwrightTestingPractice.pages.logout_orderdetails_entry import EnterOrder
from playwrightTestingPractice.pages.special_products import SpecialProducts
from playwrightTestingPractice.tests.test_07_special_products import test_click_Replenishing_LipColour


def test_click_replinishing_lip(browserInstance,common_steps,login_fixture):
    test_click_Replenishing_LipColour(browserInstance,common_steps,login_fixture)
    special_prod=SpecialProducts(browserInstance)
    
    