[pytest]
log_cli=true
log_cli_level=INFO
log_file=test.log
log_file_level=INFO
addopts=
    --screenshot=only-on-failure
    --video=retain-on-failure
    --tracing=retain-on-failure
    
asyncio_mode = auto
asyncio_default_fixture_loop_scope = session
asyncio_default_test_loop_scope = session
markers =
    no_auth: marker to run test without loading auth.json storage state