name: Playwright Pytest CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * *'   # Runs daily at 2 AM UTC (night)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          cd playwrightTestingPractice
          pip install -r requirements.txt
          playwright install

      - name: Run Pytest
        run: |
          cd playwrightTestingPractice
  
      #     pytest test_07_special_products.py

      - name: Run Tests
        run: |
          pytest -n 6 --alluredir=reports/allure-results
          continue-on-error: true   # ⭐ DO NOT FAIL PIPELINE

      - name: Install Java
        run: sudo apt-get update && sudo apt-get install default-jre -y

      - name: Install Allure CLI
        run: |
          curl -o allure.tgz -Ls https://github.com/allure-framework/allure2/releases/latest/download/allure-2.29.0.tgz
          tar -zxvf allure.tgz
          sudo mv allure-2.29.0 /opt/allure
          echo "/opt/allure/bin" >> $GITHUB_PATH

      - name: Verify Allure Install
        run: allure --version
        
      - name: Generate Allure Report
        if: always()
        run: /opt/allure/bin/allure generate allure-results -o allure-report --clean

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
