name: Playwright Pytest CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 20 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: playwrightTestingPractice
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Tests
        working-directory: playwrightTestingPractice
        run: pytest -n 6 --alluredir=reports/allure-results
        continue-on-error: true

      # 🔥 Generate Allure Report (No manual install needed)
      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: playwrightTestingPractice/reports/allure-results
          allure_report: playwrightTestingPractice/reports/allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: playwrightTestingPractice/reports/allure-report