name: Playwright Pytest CI
permissions:
    contents: write
on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 20 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: playwrightTestingPractice
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Tests
        working-directory: playwrightTestingPractice
        run: pytest -n 6 --dist=loadscope --alluredir=reports/allure-results --clean-alluredir
        continue-on-error: true

      # ✅ Install Java
      - name: Install Java
        if: always()
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre

      # ✅ Install Allure CLI (Stable)
      - name: Install Allure
        if: always()
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
          tar -zxvf allure-2.29.0.tgz
          sudo mv allure-2.29.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Get Allure history
        uses: actions/checkout@v4
        with:
            ref: gh-pages
            path: gh-pages


      - name: Copy Allure history
        run: |
          mkdir -p playwrightTestingPractice/reports/allure-results/history
          cp -r gh-pages/history/* playwrightTestingPractice/reports/allure-results/history || true

      # ✅ Generate Report
      - name: Generate Allure Report
        if: always()
        run: |
          allure generate playwrightTestingPractice/reports/allure-results \
          -o playwrightTestingPractice/reports/allure-report --clean
      - name: Save history
        run: |
          cp -r playwrightTestingPractice/reports/allure-report/history gh-pages/ || true
      # ✅ Prepare final content
      - name: Prepare GitHub Pages content
        run: |
          rm -rf gh-pages/*
          cp -r playwrightTestingPractice/reports/allure-report/* gh-pages/

      # ✅ Deploy
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
          publish_branch: gh-pages
          force_orphan: true 


      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: playwrightTestingPractice/reports/allure-report

      - name: Upload Playwright Traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: playwrightTestingPractice/test-results/

                # ✅ Add .nojekyll file (IMPORTANT)
      - name: Disable Jekyll
        if: always()
        run: touch playwrightTestingPractice/reports/allure-report/.nojekyll
 

